export const FETCH_REPOSITORY = 'FETCH_REPOSITORY'
export const FETCH_COMMITS = 'FETCH_COMMITS'
export const SEARCH_COMMITS = 'SEARCH_COMMITS'
export const LOAD_REPOSITORY_SUCCESS = 'LOAD_REPOSITORY_SUCCESS'